[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for all assets
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://*.voiceflow.com https://*.netlify.app https://maps.googleapis.com https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://*.voiceflow.com; img-src 'self' data: https://*.imgur.com https://*.brave.com https://*.wikimedia.org https://*.imghippo.com https://logos-world.net https://*.voiceflow.com https://*.googleapis.com https://*.gstatic.com https://*.ibb.co https://*.royaltransfer.eu https://*.royaltransfereu.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.royaltransfer.eu https://*.royaltransfereu.com https://*.netlify.app https://*.voiceflow.com https://*.googleapis.com https://www.google-analytics.com https://get-price-941325580206.europe-southwest1.run.app https://n8n.capohq.com; frame-src 'self' https://*.voiceflow.com https://*.stripe.com; font-src 'self' data: https://*.gstatic.com https://*.voiceflow.com; base-uri 'self'; object-src 'none'; upgrade-insecure-requests;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    
# Cache settings for immutable assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle CORS for Supabase Edge Functions
[[redirects]]
  from = "/api/email-verification/*"
  to = "https://phcqdnzuicgmlhkmnpxc.supabase.co/functions/v1/email-verification/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS"}

# Special handling for OPTIONS requests to support CORS preflight
[[redirects]]
  from = "/api/*"
  to = "https://phcqdnzuicgmlhkmnpxc.supabase.co/functions/v1/:splat"
  status = 200
  method = "OPTIONS"
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Max-Age = "86400"}