[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Headers for all assets
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
  # Cache settings for immutable assets
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.woff"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.ttf"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
  for = "/*.eot"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"